### PR TITLE
Merge Linux 5.14 (support Matias and Keychron keyboards)

### PR DESCRIPTION
**Pull request by almson**

### CODE REVIEW

**Comment by closewait** [comment]
> _No description provided._

It's already there. I submitted it yesterday.

https://lore.kernel.org/patchwork/patch/1479207/

**Comment by almson** [comment]
> > _No description provided._
> 
> I submitted it yesterday.
> 
> https://lore.kernel.org/patchwork/patch/1479207/

I'm confused. Wasn't it merged into 5.14-rc4 three weeks ago https://github.com/torvalds/linux/commit/ebe0b42a4252333aa4af60fd4d11b69405aa6068 I'm cherry-picking the upstream commit instead of making a new one (preserving authorship, etc.).

**Comment by closewait** [comment]
I am too now.

I've sent the changes based on this git repo (master) git://git.kernel.org/pub/scm/linux/kernel/git/hid/hid.git

After checking: this hid repo is not in sync with the other. I will close my pull request since it's better to keep yours.

**Comment by free5lot** [comment]
To be clear, this PR is not needed anymore as the same upstream backporting was already done in previous PR #75, am I getting it right?

**Comment by free5lot** [comment]
Sorry, I misunderstood the message of @closewait and thought this PR is not needed and going to be closed, but no one corrected me nor answered, so I did not accept it earlier.

@almson thank you for your help, merged!

**Pull request merged**
