### PR TITLE
Update with sources from kernel 5.8.x

### PR DESCRIPTION
**Pull request by jbcjorge**
Updated the source files from kernel 5.8 branch

### CODE REVIEW

**Comment by free5lot** [comment]
Thank you @jbcjorge for this PR!
I will need one additional confirmation that nothing is broken and will accept this PR. 
Maybe someone with external keyboard can check it, too.
@almson , @smaslennikov or anyone, guys?

**Comment by slavaaaaaaaaaa** [comment]
Sorry guys, I haven't had one of these keyboards in a long time.

**Comment by huseyin1419** [comment]
@free5lot
I am using Debian 5.7.10-1 kernel. When they update kernel 5.8.x, I will test. Is it okay?

**Comment by free5lot** [comment]
@ozdemir1419 yes, of course. 

By the way, you can also test `swap_fn_leftctrl` in the original 5.8 kernel, as finally this patch is making it to the upstream, starting with `swap_fn_leftctrl`.

**Comment by free5lot** [comment]
Anyone with an ability to test this rather simple PR with merge of 5.8 - please do and report if something is OK or broken for you.

**Comment by jbcjorge** [comment]
> @ozdemir1419 yes, of course.
> 
> By the way, you can also test `swap_fn_leftctrl` in the original 5.8 kernel, as finally this patch is making it to the upstream, starting with `swap_fn_leftctrl`.

Actually that I can testify it works. I'm running 5.8.2 and without the patch that was still working (actually that's the whole reason for the PR, as I got but my FN-Ctrl swap was still working, but not the Eject-Delete remap nor the right Alt-Ctrl, so I saw this needed a patch...)

**Comment by free5lot** [comment]
@jbcjorge thanks for feedback, glad to hear that the first option migrated to upstream with no issues for you.

**Comment by free5lot** [comment]
I'm merging this pull request as everything seems to be fine.

**Pull request merged**
