### PR TITLE
Added option to move fn key to F13 and make fn Insert.

### PR DESCRIPTION
**Pull request by slavaaaaaaaaaa**
Should be pretty self explanatory. At first tried to do it sanely, but your swapping tactic was a lot easier to break into submission. Thanks for making this thing!

### CODE REVIEW

**Comment by free5lot** [comment]
Thank you for your PR!

> At first tried to do it sanely, but your swapping tactic was a lot easier to break into submission.

This approach was offered in hid-apple before us, we only extend it's features.

1) Could you check your code for conflicts with simultaneous use with swap_fn_leftctrl flag? If it does conflict, maybe some "else" should be added in some places and not allow these flags to be used at once.
2) The PR code doesn't pass the Linux kernel's code requirements a bit, I could fix it for you.

> Thanks for making this thing!

You're welcome.

**Comment by slavaaaaaaaaaa** [comment]
> This approach was offered in hid-apple before us, we only extend its features.

Oh, weird, I didn't notice anything like that. Oh well. 

> 1) Could you check your code for conflicts with simultaneous use with swap_fn_leftctrl flag? If it does conflict, maybe some "else" should be added in some places and not allow these flags to be used at once.

That thought did come up a couple nights ago, it definitely looks like it should only be one or the other option (especially since, as I understand, swap_fn_leftctrl is only useful for macbooks, and swap_fn_f13 - mainly for those keyboards where fn takes place of insert. So, not macbooks. My point is, I don't think there is a scenario where someone would want to use them together). I can change that later today. 

> 2) The PR code doesn't pass the Linux kernel's code requirements a bit, I could fix it for you.

Sweet.

**Comment by almson** [comment]
@smaslennikov Will you finish this work?

**Comment by slavaaaaaaaaaa** [comment]
@almson Sorry, never got around to it. I'll look into it later this week.

**Comment by slavaaaaaaaaaa** [comment]
@free5lot looking into this further, I actually am not sure what the best way to do this is. On the bright side, I don't think there would be a scenario when one would want both flags enabled: my swap (f13 and fn, making current fn the insert key) should only be needed on the larger keyboards, while yours (fn and lctrl), on the smaller ones. I doubt the code will be happy if both are enabled, and I guess I could simply check for that and fail to load the module in this case. I'm not sure if that's an acceptable fix, however. 

The other solution is to merge the swaps together, having only one argument for it with multiple values, e.g., key_swap=1, key_swap=2, etc, defaulting to 0, which performs no swaps. This sounds like a better idea. If that works for you, I'll start working on implementing that.

**Comment by free5lot** [comment]
@smaslennikov my point was that both options used simultaneously MUST NOT crash the module ever. It's a kernel's module, so no one wants to take these chances.
So, please at least check attentively behavior if both options are used at the same time.

In my opinion if the problem will be unsolvable, the better choice would be to ignore the second option if the first is set, because it's easy and 100% safe for person who uses the module. In this case this should be mentioned in documentation of course. Maybe I'm wrong.

The good news is that I got my Macbook Pro back recently and will be able to make some checks or code modifications myself soon (but can't promise dates).

**Comment by slavaaaaaaaaaa** [comment]
I'll look into the issues with this PR later in the week.

**Comment by slavaaaaaaaaaa** [comment]
@free5lot, I made changes to simply prevent both options from being set at once. Take a look, let me know what you think. 

Alternatively, yes, we can probably just ignore one of the options if another is set. Let me know if you prefer that solution.

**Comment by slavaaaaaaaaaa** [comment]
@free5lot I jumped to conclusions that you'd rather have more checks, here they are. 

Basically, now if both swaps that involve fn key are enabled, the f13/fn swap will be ignored. I tested it locally.

**Comment by free5lot** [comment]
Thank @smaslennikov for your work!

@almson do you have a F13 key to check this PR? My macbook has only up to F12 and it's risky to accept the code without a second opinion.

**Comment by almson** [comment]
@free5lot Nope. I have a MacBook. I've never seen F13.

**Comment by slavaaaaaaaaaa** [comment]
The f13-f19 keys are present on the full-size (tenkey) keyboards. Quick googling: https://i.stack.imgur.com/2kJlU.png

**Comment by slavaaaaaaaaaa** [comment]
Rebased, cleaned up and tested again for your convenience.

**Comment by free5lot** [comment]
@smaslennikov thank you! Let me take a look in code if it could break something or not and then I will merge it. It works for you with the recent changes correctly, right?

**Comment by free5lot** [comment]
I've checked the PR, and ready to accept it. The only thing I have to change is the kernel parameter name.
Your `swap_fn_f13` seems to be a bit misleading, because it looks like other swap_* parameters, but it **does not actually swaps these 2 keys**, it makes fn to work as insert and f13 as fn.
So, the name `fn_as_insert_f13_as_fn` seems to be the most logic option, but maybe it is too long and complicated, especially when we have description of parameters, so I offer `swap_fn_f13_insert` as a compromise.

Are you OK with this option name - `swap_fn_f13_insert`? 
If it is OK with you, I will accept your patch, change the parameter's name and add information  to readme documentation about it, if not - we can discuss it.

**Comment by free5lot** [comment]
@smaslennikov your response about option name is required.

**Comment by slavaaaaaaaaaa** [comment]
@free5lot Sorry about the delay. 

>Are you OK with this option name - swap_fn_f13_insert?

Certainly. I can add the change shortly. 

>It works for you with the recent changes correctly, right?

I tested it with these last few changes, I should give it another full test though.

I have some vacation coming up, but I'll make these changes as soon as I can.

**Comment by free5lot** [comment]
@smaslennikov good to hear, I'm sorry for delay too. So, finally, should I modify your PR and apply, or should I wait for your full test and a new PR with a changed parameter name? The second would be preferable to me. Good vacation to you!

**Comment by free5lot** [comment]
@smaslennikov I'm reminding that I'm still open to get and accept this PR from you after change of parameter name and full test with the F13 keyboard by you.

**Comment by slavaaaaaaaaaa** [comment]
@free5lot I apologize (again) for delaying this. I actually don't have easy access to that keyboard anymore so testing it again will be difficult. When I have a second I'll change the name though.

**Comment by free5lot** [comment]
I understand and not in a hurry at all, just reminding, this type of keyboard and key-replacement is rather rare compared to macbook's keyboard, so do it when you have time and possibility to test.

**Comment by prook** [comment]
Testing on ubuntu 5.3.0-53-generic and magic keyboard 2 w/ numpad, with the PR applied to master.

- `swap_fn_f13=1` works as expected: `f13` becomes `fn`, `fn` becomes `insert`.
- When combined with `swap_fn_leftctrl=1`, `fn` and `leftctrl` are swapped, while `swap_fn_f13` option has no effect. This is expected as per discussion above.

I find this option very useful and would love to see it make it all the way to the upstream. If there's any more testing or anything else I could do to help, ask away!

**Comment by free5lot** [comment]
@smaslennikov hi, you have some positive feedback for this modification. Are you planing to fix the discussed issue? Maybe I can do it, but I have no f13 on macbook but this bug is probably not difficult.

**Comment by slavaaaaaaaaaa** [comment]
@prook @free5lot oh, good to know! It's been quite some time, I definitely don't have one of these keyboards with `f13` anymore. That said, as far as I can tell, the only issue left was giving this feature a better name - a change I've just pushed.

I can't test any misbehaviours but seeing @prook already has - do I owe anything else here?

**Comment by free5lot** [comment]
@smaslennikov OK, almost done then. One minor thing left - please make consistent rename of swap_fn_f13 to swap_fn_f13_insert (in upper-case too for both modified files). The rest seems to be fine to me.
After this minor change we will ask @prook to check this PR again and I will accept to the main repo.

**Comment by slavaaaaaaaaaa** [comment]
@free5lot oops, missed those. I think I've caught them all this time.

**Comment by free5lot** [comment]
@smaslennikov thanks!

@prook can you check the resulting Pull Request on your keyboard one more time and it will be accepted.

**Comment by prook** [comment]
@free5lot @smaslennikov Re-tested successfully!

The only nitpick is missing documentation in README, but I think I could follow with a PR for that as a thankyou to both of you.

**Comment by free5lot** [comment]
@prook thank you. I'm accepting this modification. Good point about documentation though.

**Pull request merged**
