### PR TITLE
Add an option to use the right Alt key as right ctrl

### PR DESCRIPTION
**Pull request by sami-mw**
This adds an option to use the right alt key as right Ctrl

### CODE REVIEW

**Comment by free5lot** [comment]
Thank you Sami for pull request, I'm going to look them though and test in 2 weeks and accept. Thanks!

**Comment by sami-mw** [comment]
@free5lot cool.. let me know if you want anything changed.

**Comment by free5lot** [comment]
Shame on me, I didn't have time to merge it with full check - as my macbook doesn't want to update kernel correctly and I should do something with it. Sorry for delay.

**Comment by sami-mw** [comment]
@free5lot thanks!

**Comment by free5lot** [comment]
@sami-mw hi, just for your information - added mention of you to the README.

**Pull request merged**
